CREATE TABLE T_USER (USER_ID INTEGER IDENTITY PRIMARY KEY,
  LOGIN VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  FIRST_NAME VARCHAR (64) NOT NULL,
  LAST_NAME VARCHAR (64) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL,
  GROUP_ID INTEGER NOT NULL);

CREATE UNIQUE INDEX IX_LOGIN ON T_USER(LOGIN);